## Lerntagebuch

**Formatierte Strings (f-Strings)** erlauben Text und Code-Outputs in einer Print-Funktion zu kombinieren.

In [50]:
print(f"Ich hatte 5 Äpfel. Dann habe ich 2 gegessen. Jetzt habe ich noch {5-2} Äpfel.")
print(f"Das Produkt aus 7 und 9 ergibt {7*9}.")

Ich hatte 5 Äpfel. Dann habe ich 2 gegessen. Jetzt habe ich noch 3 Äpfel.
Das Produkt aus 7 und 9 ergibt 63.


**Unpacking** ist ein Python-spezifisches Konzept und bedeutet, dass man mehrere Werte aus einer Datensammlung (wie einem Tupel oder einer Liste) in einem einzigen Schritt herausnehmen und direkt an separate Variablen zuweisen kann.

In [51]:
# Eine Funktion gibt zwei Werte als Tupel zurück
mein_tupel = (10, 20)

# Manuelles Zuweisen über den Index (0 und 1)
a = mein_tupel[0]  # a wird 10
b = mein_tupel[1]  # b wird 20

# Beide Variablen werden in einer einzigen Zeile "entpackt"
c, d = (10, 20)

if a == c and b == d:
    print('Unpacking hat funktioniert!')

Unpacking hat funktioniert!


**Ein Objekt** ist das grundlegende "Ding" in Python als **objekt-orientierter Programmiersprache**. Tatsächlich ist in Python absolut alles ein Objekt; es ist schlichtweg ein Datenpaket, das seine eigenen Eigenschaften (Attribute) und Fähigkeiten (Methoden) mitbringt. Mit der *type()-Funktion* lässt sich herausfinden, um weche Art von Objekt es sich handelt.

In [3]:
mein_tupel = (10, 20, 30)
print(f"{type(mein_tupel)} - Ein Tupel speichert mehrere, fest verbundene und unveränderliche Werte")

print(f"{type(3)} - Ein Integer ist eine ganzzahlige Zahl (ohne Komma)")

print(f"{type(3.14)} - Ein Float ist eine Gleitkommazahl (Zahl mit Dezimalstellen, wichtig: Punkt statt Komma!)")

text_beispiel = "Hallo EEG"
print(f"{type(text_beispiel)} - Ein String ist eine Zeichenkette (also reiner Text)")

liste_beispiel = ['Fz', 'Cz', 'Pz']
print(f"{type(liste_beispiel)} - Eine Liste speichert mehrere Werte, die im Nachhinein beliebig verändert, gelöscht oder erweitert werden können")

dict_beispiel = {'sfreq': 250, 'channels': 64}
print(f"{type(dict_beispiel)} - Ein Dictionary (Wörterbuch) speichert Daten als Schlüssel-Wert-Paare")

print(f"{type(True)} - Ein Boolean ist ein logischer Wahrheitswert (kennt nur True oder False)")

<class 'tuple'> - Ein Tupel speichert mehrere, fest verbundene und unveränderliche Werte
<class 'int'> - Ein Integer ist eine ganzzahlige Zahl (ohne Komma)
<class 'float'> - Ein Float ist eine Gleitkommazahl (Zahl mit Dezimalstellen, wichtig: Punkt statt Komma!)
<class 'str'> - Ein String ist eine Zeichenkette (also reiner Text)
<class 'list'> - Eine Liste speichert mehrere Werte, die im Nachhinein beliebig verändert, gelöscht oder erweitert werden können
<class 'dict'> - Ein Dictionary (Wörterbuch) speichert Daten als Schlüssel-Wert-Paare
<class 'bool'> - Ein Boolean ist ein logischer Wahrheitswert (kennt nur True oder False)


**Das magische Trio der objekt-orientierten Programmierung in Python**
1. **Klasse (Class)**: Der Bauplan für ein Objekt. Die Klasse legt als abstrakte Vorlage fest, welche Eigenschaften und Fähigkeiten zukünftige Objekte haben werden, die nach diesem Bauplan erstellt werden. Klassen werden meistens groß geschrieben am Anfang.

2. **Attribut (Attribute)**: Die Eigenschaften (Zustände oder Metadaten), die in einem konkreten Objekt gespeichert sind. Wichtig: Da hier keine Aktion ausgeführt wird, ruft man sie ohne Klammern am Ende auf!

3. **Methode (Method)**: Die Fähigkeiten (eingebaute Funktionen), die ein Objekt besitzt. Es sind Aktionen, die das Objekt mit sich selbst durchführen kann. Wichtig: Da hier etwas getan wird, ruft man sie immer mit Klammern () am Ende auf!

In [60]:
# ==========================================
# 1. Das Trio in Basis-Python (Wir bauen eine eigene Klasse)
# ==========================================

# KLASSE: Wir definieren den Bauplan für einen "Probanden"
class Proband:
    # Hier legen wir fest, was beim Erstellen des Objekts passiert
    def __init__(self, id_nummer, alter):
        # ATTRIBUTE: Eigenschaften, die wir im Objekt speichern
        self.id = id_nummer
        self.alter = alter
    
    # METHODE: Eine Aktion, die unser Proband ausführen kann
    def daten_liefern(self):
        return f"Proband {self.id} liefert jetzt fleißig Daten."

# Wir erstellen ein konkretes Objekt nach unserem Bauplan
p1 = Proband(id_nummer="VP_001", alter=25)

print(f"Das Objekt entspricht folgender Klasse: {type(p1)}")

# Wir rufen ein ATTRIBUT ab (Eigenschaft -> keine Klammern!)
print(f"Eigenschaft abgerufen: Der Proband ist {p1.alter} Jahre alt.")

# Wir rufen eine METHODE auf (Aktion -> mit Klammern!)
print(f"Aktion ausgeführt: {p1.daten_liefern()}")

Das Objekt entspricht folgender Klasse: <class '__main__.Proband'>
Eigenschaft abgerufen: Der Proband ist 25 Jahre alt.
Aktion ausgeführt: Proband VP_001 liefert jetzt fleißig Daten.


In [ ]:
# ==========================================
# 2. Wir untersuchen die Attribute und Methode einer Klasse
# ==========================================
alle_faehigkeiten = dir(Proband)
print(alle_faehigkeiten)
## Die Methoden mit doppelten Unterstrichen nennt man "Dunder"-Methoden (Double Underscore), die ich erstmal ignorieren darf.

# Wenn du nicht nur die Namen wissen willst, sondern auch, wie sie funktionieren:
help(Proband)

# Alternativ einfach den Namen des Objekts mit Punkt tippen und dann aus dem Drop-Down Menü auswählen

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', 'daten_liefern']
Help on class Proband in module __main__:

class Proband(builtins.object)
 |  Proband(id_nummer, alter)
 |
 |  Methods defined here:
 |
 |  __init__(self, id_nummer, alter)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  daten_liefern(self)
 |      # METHODE: Eine Aktion, die unser Proband ausführen kann
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object



25

**Indexing** bezeichnet das gezielte Abrufen von einzelnen Werten in Python und beginnt stets bei 0. Mit **Slicing** meinen wir das Abrufen von mehreren Werten gleichzeitig. 
Die grundsätzliche Syntax für Listen und Tuples ist dabei die gleiche, während Dictionaries nur über Keys ansprechbar sind.

In [53]:
# 1. LISTEN und TUPLES
# -----------------------------------------------
# Ersten Wert abrufen
print(mein_tupel[0])
print(liste_beispiel[0])

# Letzten Wert abrufen
print(mein_tupel[-1])
print(liste_beispiel[-1])

# Mehrere Werte abrufen
# Syntax: [Start:Ende] -> ACHTUNG: Das ENDE wird nicht mitgenommen!
print(f"Meine ersten zwei Kanäle erhalte ich, indem ich die Indizes 0 und 1 aufrufe: {liste_beispiel[0:2]}")

# Mehrere, nicht zusammen-hängende Werte abrufen
# print(f"Das funktioniert in Python leider NICHT: {liste_beispiel[0,2]}")

# Wir rufen Index 0 und Index 2 einzeln ab und stecken sie händisch in eine neue Liste []
auswahl_basis = [liste_beispiel[0], liste_beispiel[2]]
print(f"Basis-Python Auswahl: {auswahl_basis}")  # Gibt ['Fz', 'Pz']

# Ein flexiblerer Umgang ist möglich, wenn wir mit NumPy Arrays arbeiten. Das folgt in einem späteren Eintrag.

10
Fz
30
Pz
Meine ersten zwei Kanäle erhalte ich, indem ich die Indizes 0 und 1 aufrufe: ['Fz', 'Cz']
Basis-Python Auswahl: ['Fz', 'Pz']


In [54]:
# 3. DICTIONARIES (Ungeordnet, über Keys ansprechbar)
# ---------------------------------------------------
# Wenn man wissen will, welche Keys überhaupt existieren:
print(f"Alle Keys im Dictionary: {list(dict_beispiel.keys())}")

# Da es keine Positionen wie 0 oder 1 gibt, rufen wir den Namen des Etiketts auf
print(f"Die Sampling Rate beträgt {dict_beispiel['sfreq']} Hz")

Alle Keys im Dictionary: ['sfreq', 'channels']
Die Sampling Rate beträgt 250 Hz


In Python laden wir **Bibliotheken (Module)** wie Werkzeugkästen. Mit import X holen wir den ganzen Kasten und müssen danach immer X.werkzeug schreiben. Mit from X import Y greifen wir gezielt in den Kasten X, holen nur das Werkzeug Y (z. B. eine spezifische Klasse oder Funktion) heraus und legen es griffbereit hin, sodass wir direkt Y schreiben können.

In [ ]:
# ==========================================
# Bibliotheken importieren: import vs. from
# ==========================================
import mne
from mne_bids import BIDSPath, read_raw_bids

# 1. Was ist ein normaler Import? (Der ganze Werkzeugkasten)
print(f"{type(mne)} - Ein Modul. Das ist der große Werkzeugkasten, der alles enthält.")

# 2. Was haben wir mit 'from ... import ...' herausgeholt?
print(f"{type(BIDSPath)} - Eine Klasse! Wir haben gezielt den Bauplan für BIDS-Pfade auf den Tisch gelegt.")

print(f"{type(read_raw_bids)} - Eine Funktion! (Genau wie in R: Sie nimmt Argumente an und führt eine Aufgabe aus).")

<class 'module'> - Ein Modul. Das ist der große Werkzeugkasten, der alles enthält.
<class 'type'> - Eine Klasse! Wir haben gezielt den Bauplan für BIDS-Pfade auf den Tisch gelegt.
<class 'function'> - Eine Funktion! (Genau wie in R: Sie nimmt Argumente an und führt eine Aufgabe aus).


Um **Advanced Indexing** durchzuführen, wie ich es aus R kenne, nutzt man das Modul Numpy (np) und die darin enthaltene Array-Klasse. Hier ist es möglich, eine Liste von Indizes zu übergeben.

In [7]:
import numpy as np

# Wir wandeln unsere normale Liste in ein "NumPy Array" um (die Standard-Datenstruktur in MNE)
array_beispiel = np.array(liste_beispiel)

print(array_beispiel[[0,2]]) #Hier übergebe ich eine Liste ans Array - deshalb doppelte Klammer: Zugriff + Liste
print(array_beispiel[0:2]) # Ein Slice ist keine Liste; deshalb kann ich direkt zugreifen.
print(array_beispiel[2]) # Ein Index ist keine Liste; deshalb kann ich direkt zugreifen.

# 2D-Arrays: Indexing und Slicing (am Beispiel MNE 'events')
# ==========================================

# Wir simulieren hier ein kleines MNE 'events' Array (6 Zeilen, 3 Spalten)
events_beispiel = np.array([
    [1050, 0, 11],  # Zeile 0: Bei Sample 1050 kam Trigger 11
    [1100, 0, 22],  # Zeile 1: Bei Sample 1100 kam Trigger 22
    [1250, 0, 11],  # Zeile 2: ...
    [1400, 0, 33],
    [1550, 0, 22],
    [1600, 0, 11]
])

print(f"Die Form (Shape) des Arrays ist: {events_beispiel.shape}")


# 1. BESTIMMTE ZEILEN ABRUFEN
# -----------------------------------------------
# "Gib mir die ersten 5 Zeilen (Index 0 bis 4) und ALLE Spalten (:)"
erste_fuenf_zeilen = events_beispiel[0:5, :]
print(f"\nDie ersten 5 Zeilen komplett:\n{erste_fuenf_zeilen}")


# 2. BESTIMMTE SPALTEN ABRUFEN (Sehr wichtig in MNE!)
# -----------------------------------------------
# "Gib mir ALLE Zeilen (:), aber nur die Spalte mit dem Index 2 (die Trigger-Codes!)"
alle_trigger = events_beispiel[:, 2]
print(f"\nNur die Trigger-Codes (Spalte 2): {alle_trigger}")


# 3. DAS EINKAUFSZETTEL-PRINZIP IN 2D
# -----------------------------------------------
# "Gib mir alle Spalten (:), aber nur für die Zeile 0 und Zeile 3"
# (Erinnere dich: Einkaufszettel = innere Liste!)
gezielte_zeilen = events_beispiel[[0, 3], :]
print(f"\nNur Zeile 0 und 3:\n{gezielte_zeilen}")

['Fz' 'Pz']
['Fz' 'Cz']
Pz
Die Form (Shape) des Arrays ist: (6, 3)

Die ersten 5 Zeilen komplett:
[[1050    0   11]
 [1100    0   22]
 [1250    0   11]
 [1400    0   33]
 [1550    0   22]]

Nur die Trigger-Codes (Spalte 2): [11 22 11 33 22 11]

Nur Zeile 0 und 3:
[[1050    0   11]
 [1400    0   33]]


### Marker und Trigger in MNE-Python

**events** ist ein NumPy-Arrax mit der Shape (n_events, 3). Jede Zeile stellt ein Event dar. Die Spalten sind:

| Spalte | Bedeutung |
|  ---   |   ---     |
| [:, 0] | Sample-Zeitpunkt |
| [:, 1] | Vorheriger Event-Wert (meist 0, legacy) |
| [:, 2] | Event-ID|

In [ ]:
events[0]  # → array([  1024,  0,  110])
            #            ↑        ↑    ↑
            #          Sample  prev   ID

**event_id** ist ein Dictionairy, das als Übersetzungstabelle dient zwischen menschenlesbaren Namen und den numerischen IDs - es verbindet also Events-Matrix mit Labels.

In [ ]:
event_id = {'enc_fixation': 110, 'ret_fixation': 210}

**mne.events_from_annotations(raw, event_id={...})** ist eine Funktion, um Annotationen aus dem Raw-Objekt auszulesen, die als Text-Strings gespeichert sind, z.B. 'enc_fixation' und konvertiert sie in ihre numerische Events-Matrix - weil MNE intern immmer mit Zahlen arbeitet.

Die Funktion wende ich immer wieder an, da ich nur die Events extrahiere, die ich gerade brauche - durch den *event_id*-Parameter filtere ich gleichzeitig & verhindere den 10.000er-Offset.

In [ ]:
# Nur enc_fixation → sauber, kein Offset
events, _ = mne.events_from_annotations(raw_eeg, event_id={'enc_fixation': 110})

## Cheat Sheet Git commands

In [1]:
# Paste the following commands into the terminal
# git add .
# git commit -m 'description of changes'
# git push